version: '2.1'
services:    
    backend:
        build: ./
        environment:
        - NODE_ENV=production
        - PORT=3030
        ports:
        - "3030"
        volumes:
        - "./app/logs:/usr/src/app/log"
        - "./app/defaults:/usr/src/app/defaults"
        - "./app/uploads:/usr/src/app/uploads"        
        restart: always
        links:
        - mongodb-primary
        depends_on:          
          mongodb-primary:
            condition: service_healthy
          mongodb-secondary:
            condition: service_healthy
        healthcheck:
          test: ["CMD", "curl", "-k", "-H", "Origin: http://localhost", "http://localhost:3030/api/v1/healthcheck"]
          interval: 30s
          timeout: 10s
          retries: 5

    fix-mongodb-permissions:
      image: 'bitnami/mongodb:latest'
      user: root
      command: chown -R 1001:1001 /bitnami
      volumes:
        - ./app/mongo_data:/bitnami

    # Default ReplicaSet Name : replicaset
    mongodb-primary:
        image: 'bitnami/mongodb:latest'
        ports:
        - "27017"
        environment:
          - MONGODB_REPLICA_SET_MODE=primary
          - MONGODB_ROOT_PASSWORD=password123
          - MONGODB_REPLICA_SET_KEY=replicasetkey123
          - MONGODB_USERNAME=user
          - MONGODB_PASSWORD=password
          - MONGODB_DATABASE=framework
          - MONGODB_SYSTEM_LOG_VERBOSITY=1
        volumes:
          - './app/mongo_data:/bitnami'
        healthcheck:
          test: ["CMD", "echo", "db.runCommand('ping').ok", "| mongo localhost:27017/framework --quiet"]
          interval: 30s
          timeout: 10s
          retries: 5
          

    mongodb-secondary:
        image: 'bitnami/mongodb:latest'
        depends_on:          
          mongodb-primary:
            condition: service_healthy
        environment:
          - MONGODB_REPLICA_SET_MODE=secondary
          - MONGODB_PRIMARY_HOST=mongodb-primary
          - MONGODB_PRIMARY_PORT_NUMBER=27017
          - MONGODB_PRIMARY_ROOT_PASSWORD=password123
          - MONGODB_REPLICA_SET_KEY=replicasetkey123
          - MONGODB_SYSTEM_LOG_VERBOSITY=1
        healthcheck:
          test: ["CMD", "echo", "db.runCommand('ping').ok", "| mongo localhost:27017/framework --quiet"]
          interval: 30s
          timeout: 10s
          retries: 5

    mongodb-arbiter:
        image: 'bitnami/mongodb:latest'
        depends_on:          
          mongodb-primary:
            condition: service_healthy
        environment:
          - MONGODB_REPLICA_SET_MODE=arbiter
          - MONGODB_PRIMARY_HOST=mongodb-primary
          - MONGODB_PRIMARY_PORT_NUMBER=27017
          - MONGODB_PRIMARY_ROOT_PASSWORD=password123
          - MONGODB_REPLICA_SET_KEY=replicasetkey123
          - MONGODB_SYSTEM_LOG_VERBOSITY=1
        healthcheck:
          test: ["CMD", "echo", "db.runCommand('ping').ok", "| mongo localhost:27017/framework --quiet"]
          interval: 30s
          timeout: 10s
          retries: 5