module.exports = {
  JWT: {
    secret: 'helloWorld',
    refreshTokenSecret: 'helloworld!',
    tokenLife: 900,
    refreshTokenLife: 86400,
  },
  ssl: false,
  application_id: 'backend_01',
  host: '127.0.0.1:3030',
  origin: [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3001',
    'http://localhost:3001',
  ],
  port: 3030,
  socketio: 3031,
  version: '/api/v1',
  path: '/Users/tgingras/Documents/Studiowebux/Node-framework/backend',
  author: 'Studio Webux S.E.N.C',
  project: 'Node Framework',
  ver: '1.4.1',
  enterprise: 'Studio Webux',
  sslkey: '/ssl/ssl.key',
  sslcert: '/ssl/ssl.crt',
  morgan: {
    type: 'combined',
    filename: 'access.log',
    rotate: '1d',
    path: 'log',
  },
  logger: {
    logstash: {
      enabled: false,
      port: '5000',
      name: 'Backend',
      host: '127.0.0.1',
    },
  },
  proxy_list: '127.0.0.1',
  bodyParser: {
    extended: true,
    limit: '10mb',
  },
  authentication: {
    accountActivationRequired: false,
    autoLoginOnSignUp: true,
    passwordStrategy: {
      passwordRegex:
        '^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{8,}$',
      regexMessage:
        'Minimum eight(8) characters, at least one(1) letter, one(1) number and one(1) special character.',
      regexEnabled: false,
    },
    ldap: {
      url: 'ldaps://openldap.webux.lab:636',
      bindDN: ',ou=Users,dc=webux,dc=lab',
      searchBase: 'dc=webux,dc=lab',
      searchAttributes: ['mail', 'uid', 'displayName', 'preferredLanguage'],
      cacert: '/ssl/root_ca_cert.crt',
    },
    facebook: {
      appID: 'CHECK_FACEBOOK',
      appSecret: 'CHECK_FACEBOOK',
      callbackURL: '/api/v1/auth/facebook/callback',
    },
  },
  sm: {
    enabled: false,
    pwd: 'PASSWORD',
    user: 'USERNAME',
    host: 'smtp.provider.xxx',
    port: 465,
    secure: true,
    FROM: 'Framework <no-reply@framework.com>',
    STAFF: 'Framework <support@framework.com>',
  },
  authy: {
    key: 'CHECK_AUTHY',
    sid: 'CHECK_AUTHY',
    token: 'CHECK_AUTHY',
    number: 'CHECK_AUTHY',
  },
  disableAuth: true,
  redis: {
    host: '127.0.0.1',
    port: '6379',
    auth_pass: '',
    no_ready_check: true,
  },
  db: {
    local: true,
    defaultValues: true,
    debug: true,
    URL: '@127.0.0.1:27017/framework',
    user: '',
    password: '',
    RepSet: '',
    overwrite: true,
  },
  locales: {
    default: 'fr',
    availables: ['fr', 'en'],
    directory: 'locales',
    cookie: 'lang',
    autoReload: true,
    syncFiles: true,
  },
  fileUpload: {
    limits: {
      fileSize: '1024*1024*10',
    },
    abortOnLimit: true,
    safeFileNames: true,
    size: 200,
    destination: '.tmp',
  },
  cache: {
    enabled: false,
  },
  limiter: {
    enabled: false,
    auth: 3600,
    global: 60,
    globalReq: 150,
    authReq: 5,
  },
};
