module.exports = {
  JWT: {
    secret: process.env.JWT_SECRET,
    refreshTokenSecret: process.env.JWT_REFRESH_SECRET,
    tokenLife: 900,
    refreshTokenLife: 86400,
  },
  ssl: false,
  application_id: process.env.APP_ID,
  host: process.env.HOST,
  origin: ['http://localhost:3000', 'http://127.0.0.1:3000'],
  port: process.env.PORT || 3030,
  socketio: process.env.SOCKET_PORT || 3001,
  version: '/api/v1',
  path: process.env.PATH,
  author: 'Studio Webux S.E.N.C',
  project: 'Node Framework',
  enterprise: 'Studio Webux',
  sslkey: process.env.SSL_KEY,
  sslcert: process.env.SSL_CRT,
  morgan: {
    type: 'combined',
    filename: 'access.log',
    rotate: '1d',
    path: 'log',
  },
  logger: {
    logstash: {
      enabled: true,
      port: '5000',
      name: 'Backend',
      host: '127.0.0.1',
    },
  },
  proxy_list: '127.0.0.1',
  bodyParser: {
    extended: true,
    limit: '10mb',
  },
  authentication: {
    accountActivationRequired: true,
    autoLoginOnSignUp: false,
    passwordStrategy: {
      passwordRegex:
        '^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{8,}$',
      regexMessage:
        'Minimum eight(8) characters, at least one(1) letter, one(1) number and one(1) special character.',
      regexEnabled: false,
    },
    ldap: {
      url: process.env.LDAP_URL,
      bindDN: process.env.LDAP_DN,
      searchBase: process.env.LDAP_BASE,
      searchAttributes: ['mail', 'uid', 'displayName', 'preferredLanguage'],
      cacert: process.env.LDAP_CA,
    },
    facebook: {
      appID: process.env.FB_APP_ID,
      appSecret: process.env.FB_APP_SECRET,
      callbackURL: '/api/v1/auth/facebook/callback',
    },
  },
  sm: {
    enabled: false,
    pwd: process.env.MAIL_PASSWORD,
    user: process.env.MAIL_USERNAME,
    host: process.env.MAIL_HOST,
    port: 465,
    secure: true,
    FROM: 'Framework <no-reply@framework.com>',
    STAFF: 'Framework <support@framework.com>',
  },
  authy: {
    key: process.env.AUTHY_KEY,
    sid: process.env.AUTHY_SID,
    token: process.env.AUTHY_TOKEN,
    number: process.env.AUTHY_NUMBER,
  },
  disableAuth: true,
  redis: {
    host: '127.0.0.1',
    port: '6379',
    auth_pass: process.env.REDIS_PASSWORD,
    no_ready_check: true,
  },
  db: {
    local: true,
    defaultValues: true,
    debug: false,
    URL: process.env.MONGO_URL || '@127.0.0.1:27017/framework',
    user: process.env.MONGO_USER,
    password: process.env.MONGO_PASSWORD,
    RepSet: process.env.MONGO_REPLICA_SET,
    overwrite: true,
  },
  locales: {
    default: 'fr',
    availables: ['fr', 'en'],
    directory: '/locales',
    cookie: 'lang',
    autoReload: true,
    syncFiles: true,
  },
  fileUpload: {
    limits: {
      fileSize: '1024*1024*10',
    },
    abortOnLimit: true,
    safeFileNames: true,
    size: 200,
    destination: '.tmp',
  },
  cache: {
    enabled: false,
  },
  limiter: {
    enabled: false,
    auth: 3600,
    global: 60,
    globalReq: 150,
    authReq: 5,
  },
};
